### PR TITLE
Added Auto Join Google Meet

### PR DESCRIPTION
**Pull request by Ashking009**
An automation python program that will auto-join a google meet.

### CODE REVIEW

**Comment by Ankitr19** [comment]
Nice one @Ashking009, one small suggestion, in future just explore `driver.execute_script`, basically it will execute javascript code in the web-browser. It's a bit faster than using `x-path`.

**Review by Ankitr19 — APPROVED** [review]
Would be great if you can wrap each and every action in a function, like logging into StackOverflow as a function, and then call them via the `main` method. It makes the code looks much cleaner.

**Review by Ashking009 — COMMENTED** [review]
Cleaned code by adding required functions

**Comment by iu-sh** [comment]
Please raise an issue first.

**Pull request merged**
