### PR TITLE
DSA code in (Palindrome) Python & (Bubble Sort) C++

### PR DESCRIPTION
**Pull request by itsDigvijaysing**
Palindrome python code in DSA folder

### CODE REVIEW

**Comment by itsDigvijaysing** [comment]
If there is any issue, i would fix it as soon as possible

**Comment by itsDigvijaysing** [comment]
This pull request contain
palindrome code in python
bubble sort code in cpp

**Comment by iu-sh** [comment]
BubbleSort is already present at https://github.com/DSC-NITA/HacktoberFest2020/tree/master/DSA/Algorithms/Sorting-Searching/Sorting and Palindrome is too basic to be merged.

**Comment by itsDigvijaysing** [comment]
> BubbleSort is already present at https://github.com/DSC-NITA/HacktoberFest2020/tree/master/DSA/Algorithms/Sorting-Searching/Sorting and Palindrome is too basic to be merged

Thank you for your review, plz can you suggest me which type of algorithm should i create next to get pull request accepted...
Because nearly all type are algorithm are present here, so I am little confused what to create next, It will be great if You suggest me anything.

**Comment by iu-sh** [comment]
Well... I mean the "Hashmap" folder is still empty, you can add some programs to that or the Graphs folder still lacks many Algo like Prims Spanning Tree, Krushkals, Bellman-Ford... just to name a few.

**Pull request closed without merging**
